
pluto:
  node:   localhost
  logger: stdout # syslog

pluto-disco:
  endpoint: "localhost:8000"

pluto-supervisor:
  register: "localhost:8000"
  services:
    - pluto-disco
    - pluto-dashboard
    - pluto-varnish
    - pluto-monitor

pluto-monitor:
  register: "localhost:8000"

pluto-dashboard:
  register: "localhost:8000"
  
  localhost:
    app-001:
      concurrency:
        web: 3
    
  machine-009.mrhenry.be:
    band-it:
      environment:
        RAILS_ENV: production
      concurrency:
        web: 5
      hostnames:
        - band-it.be
        - band-it.fr
        - band-it.nl

    b-token:
      backends:
        - "localhost:3000"
      hostnames:
        - b-token.eu

pluto-varnish:
  register: "localhost:8000"
  
  config_file: "/etc/varnish/default.vcl"
  reload_cmd:  "/etc/init.d/varnish reload"
  
  fallback:
    host: "machine-003.mrhenry.be"
    port: 8081
