
localhost:
  app-001:
    environment:
      RACK_ENV: production
    concurrency:
      web: 1
    hostnames:
      - localhost

machine-009.mrhenry.be:
  band-it:
    environment:
      RAILS_ENV: production
    concurrency:
      web: 5
    hostnames:
      - band-it.be
      - band-it.fr
      - band-it.nl

  b-token:
    backends:
      - "localhost:3000"
    hostnames:
      - b-token.eu
